### ISSUE TITLE
ordersSubscription returns error

### ISSUE THREAD

**Issue by thetre97** [CommerceQL/commerceql#15]
### Firstly, thanks for this boilerplate - is extremely helpful!

---

I have just created a project and tried running the subscriptions example in the README:
```bash
subscription {
  ordersSubscription {
    node {
      id
      email
      total
    }
    updatedFields
    previousValues {
      id
      email
      total
    }
  }
}
```

But it returns this error: 
```bash
{
  "errors": [
    {
      "message": "Cannot read property 'args' of undefined",
      "locations": [
        {
          "line": 2,
          "column": 3
        }
      ],
      "path": [
        "ordersSubscription"
      ]
    }
  ]
}
```

Could you explain what I am doing wrong here, or is it an error with the code?

Thanks!

**Comment by notrab** [comment]
Hi @thetre97 

Thanks for reporting this. I believe this is a two part, the first being the schema defintion for Subscription should be...

```graphql
ordersSubscription: OrderSubscriptionPayload!
```

Should be 

```graphql
ordersSubscription: OrderSubscriptionPayload
```

And the second issue I think is with Prisma 1.7. I'm checking with those guys on this and will report back.

Thanks for the feedback 👍 Appreciate it

**Comment by notrab** [comment]
Hi @thetre97 

I've updated the repo that improves the subscriptions.
