### ISSUE TITLE
AppSync Integration

### ISSUE THREAD

**Issue by kosirm** [CommerceQL/commerceql#17]
Hi, thank you for this project and for many great video tutorials on YouTube! It is an eye-opening work for me!
I would like to use your project with [AWS AppSync](https://aws.amazon.com/appsync/), which is an AWS Managed GraphQL Service to build "scalable & reliable GraphQL endpoint with Serverless". 
I'm learning about it from this 3-part tutorial ([Second part here](https://hackernoon.com/running-a-scalable-reliable-graphql-endpoint-with-serverless-24c3bb5acb43)).
Do you see any possibility to upgrade your project to allow such configuration? Can you give me some advice, what should be done (I'm a beginner in both graphql and appsync)? Thanks.

**Comment by notrab** [comment]
Hi @kosirm 

Thanks for the kind words.

CommerceQL was designed to work with Prisma and be a boilerplate for those looking to get started with that. I'd love to support AppSync in the future but it may be better suited as a fork of this project 😄

**Comment by kosirm** [comment]
That's what I was expecting, but you know "it's better to ask"... Thanks for the reply!
Honestly, right now I'm learning about Stripe Relay integration (mentioned in the tutorial) for inventory & order management features. Since Relay API offers also social, voice or messenger bot integrations and possibility that I can offload this all together from my back looks attractive.

**Comment by notrab** [comment]
@kosirm great!

I'm working on a [Moltin](moltin.com) integration that will offload the data to Moltin instead of Prisma but, again it may come in the format of another repo 🎉
