### ISSUE TITLE
Create Payment type

### ISSUE THREAD

**Issue by notrab** [CommerceQL/commerceql#8]
A `Payment` should belong to an `Order`.

`Payment`'s can be successful, declined and refunded.

**Comment by agustif** [comment]
I would like to be able to make partial payments of an order, and to have a minimum to make the order, like 20% upfront 80% 2 months before trip

**Comment by notrab** [comment]
Hi @agustif 

You could handle this with some basic logic inside the checkout mutation and then another mutation for `pay` which can take in an amount and apply those.

This is just a boilerplate so you're free to adapt to your needs 😄

**Comment by agustif** [comment]
Thanks Jamie, I'm actually just gonna do that.

How should I approach it tho, any way to -ensure- it will be easy for me to update the code? Or should I just use it as an starting point and move with my own set up from there on

**Comment by notrab** [comment]
Hi @agustif 

I'm in the process of splitting up the `checkout` mutation so that `token` is optional.

Then you'll be able to call another mutation called `pay` that expects `orderId` and `token` args to complete the payment.

Then you'd be able to handle the logic you require 😄
